# Generated by Django 4.2.3 on 2023-07-14 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventes', '0004_demandeachat_traitee_alter_vente_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.vente')),
            ],
        ),
        migrations.AddField(
            model_name='vente',
            name='comments',
            field=models.ManyToManyField(related_name='vente_comments', through='ventes.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
