# Generated by Django 4.2.3 on 2023-07-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
