# Generated by Django 4.2.3 on 2023-07-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0007_vente_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='slug',
        ),
    ]
