# Generated by Django 4.2.3 on 2023-07-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0008_remove_vente_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vente',
            name='categories',
            field=models.ManyToManyField(to='ventes.categorie'),
        ),
    ]
