# Generated by Django 4.2.3 on 2023-07-18 18:45

from django.db import migrations, models
import ventes.models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0009_categorie_vente_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(default='', upload_to=ventes.models.upload_to),
        ),
    ]
