# Generated by Django 4.2.3 on 2023-07-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0010_categorie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
