# Generated by Django 4.2.3 on 2023-07-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0012_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='image',
        ),
    ]
