# Generated by Django 4.2.3 on 2023-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_room_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
