# Generated by Django 4.2.2 on 2023-07-08 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_acheteurprofile_acheteurvendeurprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpyMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadgets', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='acheteurprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='acheteurvendeurprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendeurprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Acheteur',
        ),
        migrations.DeleteModel(
            name='AcheteurVendeur',
        ),
        migrations.DeleteModel(
            name='Vendeur',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Spy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('SPY', 'Spy'), ('DRIVER', 'Driver')], default='SPY', max_length=50, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='AcheteurProfile',
        ),
        migrations.DeleteModel(
            name='AcheteurVendeurProfile',
        ),
        migrations.DeleteModel(
            name='VendeurProfile',
        ),
        migrations.AddField(
            model_name='spymore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivermore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
