# Generated by Django 4.2.3 on 2023-07-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_acheteurprofile_acheteurvendeurprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ACHETEUR', 'Acheteur'), ('VENDEUR', 'Vendeur'), ('ACHETEUR_VENDEUR', 'AcheteurVendeur')], default='ACHETEUR', max_length=50),
        ),
    ]
